version: '3.7'

services:
    web:
        build: 
            context: .
            target: dev
        volumes:
            - ./html/:/usr/local/apache2/htdocs/:ro
        networks:
            - nginxproxygitdeploy_net-proxy

networks:
    nginxproxygitdeploy_net-proxy:
        external: true